package StringToUppercaseApp;


/**
* StringToUppercaseApp/StringUppercase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringUppercase.idl
* Monday, 28 April, 2025 12:27:48 AM IST
*/

public interface StringUppercase extends StringUppercaseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StringUppercase
