package StringToUppercaseApp;


/**
* StringToUppercaseApp/StringUppercaseHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringUppercase.idl
* Monday, 28 April, 2025 12:27:48 AM IST
*/

abstract public class StringUppercaseHelper
{
  private static String  _id = "IDL:StringToUppercaseApp/StringUppercase:1.0";

  public static void insert (org.omg.CORBA.Any a, StringToUppercaseApp.StringUppercase that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static StringToUppercaseApp.StringUppercase extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (StringToUppercaseApp.StringUppercaseHelper.id (), "StringUppercase");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static StringToUppercaseApp.StringUppercase read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_StringUppercaseStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, StringToUppercaseApp.StringUppercase value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static StringToUppercaseApp.StringUppercase narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof StringToUppercaseApp.StringUppercase)
      return (StringToUppercaseApp.StringUppercase)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      StringToUppercaseApp._StringUppercaseStub stub = new StringToUppercaseApp._StringUppercaseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static StringToUppercaseApp.StringUppercase unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof StringToUppercaseApp.StringUppercase)
      return (StringToUppercaseApp.StringUppercase)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      StringToUppercaseApp._StringUppercaseStub stub = new StringToUppercaseApp._StringUppercaseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
