package StringToUppercaseApp;

/**
* StringToUppercaseApp/StringUppercaseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringUppercase.idl
* Monday, 28 April, 2025 12:27:48 AM IST
*/

public final class StringUppercaseHolder implements org.omg.CORBA.portable.Streamable
{
  public StringToUppercaseApp.StringUppercase value = null;

  public StringUppercaseHolder ()
  {
  }

  public StringUppercaseHolder (StringToUppercaseApp.StringUppercase initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StringToUppercaseApp.StringUppercaseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StringToUppercaseApp.StringUppercaseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StringToUppercaseApp.StringUppercaseHelper.type ();
  }

}
