package StringUppercaseApp;

/**
* StringUppercaseApp/StringUppercaseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringUppercase.idl
* Monday, 28 April, 2025 12:36:07 AM IST
*/

public final class StringUppercaseHolder implements org.omg.CORBA.portable.Streamable
{
  public StringUppercaseApp.StringUppercase value = null;

  public StringUppercaseHolder ()
  {
  }

  public StringUppercaseHolder (StringUppercaseApp.StringUppercase initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StringUppercaseApp.StringUppercaseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StringUppercaseApp.StringUppercaseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StringUppercaseApp.StringUppercaseHelper.type ();
  }

}
