package StringReverseApp;


/**
* StringReverseApp/StringReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringReverse.idl
* Monday, 28 April, 2025 12:00:51 AM IST
*/

public interface StringReverseOperations 
{
  String reverseString (String inputStr);
} // interface StringReverseOperations
